# site settings
title: Taimoor
subtitle: by Taimoor
email: ranatamoor067@gmail.com
description: This is a website for personal blogging: # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Taimoor
street_address:
city: Fsd
state: Pakistan
zip_code: 
country: Pakistan
phone: 23457990

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url: 
github_url: 
gitlab_url: 
googleplus_url:
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
